// Auto-generated image placeholders (low quality image placeholders)
export const LQIP: Record<string, string> = {
  "hero.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAVABADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAQb/xAAdEAACAgIDAQAAAAAAAAAAAAABAgADBCEGERMF/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAaEQACAgMAAAAAAAAAAAAAAAAAARExMkFh/9oADAMBAAIRAxEAPwB7JFVWEGZgpI6EawHDYCLWwbe5zPIbLF8RsKBKXFPQ1OWJKmRqSuGcirVwikaEqfIrWrDrVB12IQg8UKs//9k=",
  "ikea-sweden.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAJABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQT/xAAdEAABBAIDAAAAAAAAAAAAAAABAAIDBAUhMUFF/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAXEQADAQAAAAAAAAAAAAAAAAAAARES/9oADAMBAAIRAxEAPwBlliR3ACPORkNl8RGwranaN9OVVphEf//Z",
  "ikea-team.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMF/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIDBAARBTESEyFB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8ApZ5COIH1AMBgbkorNU+A0w/My5nK11A197xVEVYm0O8ELH//2Q==",
  "ikea-presentation.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBv/EACAQAAIABgIDAAAAAAAAAAAAAAEDAAIEBREhIjEjQaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGREAAwADAAAAAAAAAAAAAAAAAAESESFB/9oADAMBAAIRAxEAPwAVcFK2wch9h9Ne5KtpW2QSD0Yz1QMzZPeYvVTL8Qwd97gLeNiyuH//2Q==",
  "kama-superstars.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQb/xAAfEAACAQQCAwAAAAAAAAAAAAABAgADBAURFCEiQVH/xAAVAQEBAAAAAAAAAAAAAAAAAAABBP/EABoRAAICAwAAAAAAAAAAAAAAAAABAgMRISL/2gAMAwEAAhEDEQA/AKDK3HHAcHxgFxk3r1VFJie4pkRu2Kk7B+wjHUkDt17lda5GWng//9k=",
  "workshop-session.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQb/xAAfEAACAQQCAwAAAAAAAAAAAAACAwEABSExBBEGEkL/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQACEv/aAAwDAQACEQMRAD8AUddiaUigCIZjdTd0Q0Wywg6jeaasbSPiF7dY1ijfImmXBzP1QGlZeQv/2Q==",
  "networking-event.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBv/EABwQAAICAwEBAAAAAAAAAAAAAAECAxEABAYSQf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAABACH/2gAMAwEAAhEDEQA/AGnpJYJliUWKy6bo1OuPLgP9GZpkDb5sYO9AgUUKs4RySX//2Q==",
  "global-exposure.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIE/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIDBAARQQUSITFC/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABURAQEAAAAAAAAAAAAAAAAAAABh/9oADAMBAAIRAxEAPwAaluaBG7Pn3miXqctqqVLE8ZEqhK7lRzh1UUV9geSd4g//2Q==",
  "conference-moment.jpg": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAjABADASIAAhEBAxEB/8QAGQAAAwADAAAAAAAAAAAAAAAAAAQFAQID/8QAIxAAAQQBAwQDAAAAAAAAAAAAAQACAwQRBRIxEyEiQTJCUf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAGREAAgMBAAAAAAAAAAAAAAAAABEBAiEy/9oADAMBAAIRAxEAPwCXpmnylvWbkNHKZlsBx8JywjkKhATHA2Nv2/ErPQZsc3AyfaJjpm00gpR7i7JHCmQ2pbMp3uwMrGp9U2CCfD0le8QyqaUxySzbVAzqDibmCey4WPiEIS15Dno//9k="
};

export const DIMENSIONS: Record<string, { w: number; h: number }> = {
  "hero.jpg": {
    "w": 960,
    "h": 1280
  },
  "ikea-sweden.jpg": {
    "w": 1400,
    "h": 787
  },
  "ikea-team.jpg": {
    "w": 1400,
    "h": 1050
  },
  "ikea-presentation.jpg": {
    "w": 1400,
    "h": 1050
  },
  "kama-superstars.jpg": {
    "w": 1032,
    "h": 774
  },
  "workshop-session.jpg": {
    "w": 1400,
    "h": 1050
  },
  "networking-event.jpg": {
    "w": 1400,
    "h": 1050
  },
  "global-exposure.jpg": {
    "w": 1400,
    "h": 1050
  },
  "conference-moment.jpg": {
    "w": 1400,
    "h": 3038
  }
};
